#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Jan Betzing

# Short bio or description (displayed in the header)
description: >
  [Researcher](https://www.wi.uni-muenster.de/department/groups/is/people/jan-betzing) in Information Systems at [ERCIS](https://twitter.com/ercisorg)
  at [WWU Münster](https://twitter.com/WWU_Muenster),
  software engineer at [Weggerockt Development](/about/), <br />
  and [music enthusiast](https://last.fm/user/Balauue) at all times.

# Short description for meta tags and feed
metadescription: >
  Jan Betzing is researcher in Information Systems at the ERCIS at WWU Münster,
  software engineer at Weggerockt Development, and music enthusiast.

email: jan@rck.ms

#Top left icon
icon: "/assets/images/icon.png"
# Main page icon
logo: https://avatars3.githubusercontent.com/u/301907?v=3&s=500
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Jan Betzing'
author: 'Jan Betzing'
bio: >
  Researcher, PhD Student, Software Engineer, Jekyll Beginner

# URL of your avatar or profile pic (you could use your GitHub profile pic)
author_image: https://avatars3.githubusercontent.com/u/301907?v=3&s=500

paginate:	5
#
# Flags below are optional
#

# social icons and sharing options
social:
  - icon:	xing
    url:	https://xing.com/
    desc: Connect with me on Xing
    share_url:
    share_title:
    share_link:

  - icon:	facebook
    url:	https://facebook.com/balauue
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/balauue
    desc:	Find me on github
    share_url:
    share_title:
    share_link:

  - icon:	lastfm
    url:	https://last.fm/user/Balauue
    desc:	Connect with me on last.fm
    share_url:
    share_title:
    share_link:

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 'rckms'

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 'UA-65113531-1'

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: 'https://balauue.github.io'

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
